### ISSUE TITLE
Why CTRL+C is considered as unclean shutdown

### ISSUE THREAD

**Issue by khelle** [bitshares/bitshares-core#361] opened 2017-08-16 10:36 UTC
As the title says - why CTRL+C is considered as unclean shutdown ?

**Comment by oxarbitrage** [comment] 2017-08-16 12:06
ctrl-c is not considered an unclean shuhtdown, the problem is sometimes it fails depending on what stage of the chain it was called. if you are short of memory the ctrl-c will never end. there are also other problems.

ctrl-c problems are also discussed at https://github.com/bitshares/bitshares-core/pull/339

**Comment by pmconrad** [comment] 2017-08-16 16:04
Where does it say that CTRL-C is an unclean shutdown? CTRL-C/SIGTERM is actually the correct way to do a clean shutdown.

**Comment by khelle** [comment] 2017-08-17 11:59
Whenever I use CTRL+C to shutdown my witness node , the next time it starts its says "unclean shutdown detected". I do not spam CTRL+C to close it. I press it exactly once, and wait until it stops.

**Comment by oxarbitrage** [comment] 2017-08-17 16:16
how are you starting the node ? you could be short of ram, consider using a few start options to reduce blockchain size and ram, something like:

`programs/witness_node/witness_node --rpc-endpoint "127.0.0.1:8090" --max-ops-per-account 100 --partial-operations true`

**Comment by oxarbitrage** [comment] 2017-08-28 23:30
no further response. closing.

**Closed by oxarbitrage** 2017-08-28 23:30 UTC
