### ISSUE TITLE
Not match orders on ALIBABACOM/BTS

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-core#911] opened 2018-05-11 05:38 UTC
![default](https://user-images.githubusercontent.com/6587277/39908371-8094470a-54f6-11e8-8054-b719ea189e38.png)
On this asset now margin call and margin order not matched with orders from sell depth

**Comment by akledirs** [comment] 2018-05-11 12:07
Such problem there is BOEINGCOM/BTS and NETFLIXCOM/BTS

**Comment by pmconrad** [comment] 2018-05-11 13:38
We have fixed various issues wrt margin call handling in the upcoming hardfork. Most likely your reports are covered by this.

**Comment by abitmore** [comment] 2018-05-11 19:07
Duplicate of https://github.com/bitshares/bitshares-core/issues/606.

Fixed with https://github.com/bitshares/bsips/blob/master/bsip-0034.md .

@akledirs the fix is out. Please help test. More info: https://steemit.com/bitshares/@abit/bitshares-testnet-release-test-2-0-180510

**Closed by abitmore** 2018-05-11 19:07 UTC
Labels: 0 Duplicate, bug
