### ISSUE TITLE
get_ticker returning "inf" for latest and percent_change

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-core#505] opened 2017-11-26 13:26 UTC
I'm working on replacing the old market stats calculations of the GUI with calls to get_ticker and ran into some cases where the API returns "inf" values.

![image](https://user-images.githubusercontent.com/6890015/33240401-95e44af6-d2b5-11e7-81d3-005d54de7c0f.png)

**Comment by abitmore** [comment] 2017-11-26 14:50
@svk31 try develop branch of bitshares-core?

**Comment by abitmore** [comment] 2017-11-26 14:54
It should have been fixed in https://github.com/bitshares/bitshares-core/pull/455

**Comment by abitmore** [comment] 2017-11-26 15:04
By the way, this "inf" data is caused by a "nothing for something" scenario due to rounding issues.

On block 22127637, gold-star paid 0 BTC for 0.0004 CNY from x-bot (http://cryptofresh.com/tx/ae7f6770e96bf486c5381402e93d65c5729bde13).

Related issues: #132, #184.

**Comment by abitmore** [comment] 2017-12-11 10:37
Should have been fixed. Closing. Feel free to reopen or open a new ticket if there are still issues.

**Closed by abitmore** 2017-12-11 10:37 UTC
Labels: api, bug
