### ISSUE TITLE
Cleanup unused `fork_database::_unlinked_index`?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#939] opened 2018-05-21 12:35 UTC
According to code: https://github.com/bitshares/bitshares-core/blob/bf263b1db47a91ea9748118df1abb5a22cafc40b/libraries/chain/fork_database.cpp#L68-L69

`_unlinked_index.insert(...)` should have never been called.

I guess we can remove the member variable `_unlinked_index`?

**Comment by jmjatlanta** [comment] 2018-05-21 13:32
It appears to me that if you attempt to push a block that is unlinkable, it should go in here. ``_push_block()`` will remove it from this collection if the problem is later resolved.

But meanwhile, it is used by ``is_known_block()`` and ``fetch_block()``.

So, without understanding all the mechanics, I would think that we should find out the intent of this collection, and if it is valid functionality, swap lines 68 and 69. If the intent is invalid, then I agree, remove ``_unlink_index``.

To answer the question above, I need to know what causes an ``unlinkable_block_exception`` that is only temporary, and may later get resolved. I am researching, but if you know off the top of your head, please point me in the right direction.

**Comment by abitmore** [comment] 2018-05-21 13:46
This is low priority. We'll discuss later.

By now, please primarily focus on things in 201806 hf milestone; if nothing is there, work on things in 201806 non-hf milestone (quite some are there but I think we have to postpone some, so please spend time selectively). Deadline is this Wednesday/Thursday.

**Comment by pmconrad** [comment] 2018-05-22 16:36
If you receive blocks in order 1, 3, 2 then you'll get an unlinkable exception when trying to push 3 (because it is based on 2, but you haven't seen 2 yet).

**Comment by pmconrad** [comment] 2018-11-08 16:57
Will be resolved by #1360

**Comment by pmconrad** [comment] 2019-03-01 14:14
#1360 was in recent feature release. Closing.

**Closed by pmconrad** 2019-03-01 14:14 UTC
Labels: 1c Task, 2a Discussion Needed, 3c Enhancement, 4a Low, code cleanup, low priority
