### ISSUE TITLE
Order placed inconsistant with market price

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-core#408] opened 2017-09-27 15:25 UTC
Today at 17:03 there was an order placed on the OPEN.BTC/bitUSD market that wasn't consistent with the market prices. 

The market has buy at ~3.785 and sell at ~3.867.
Somehow an order was placed on the market with the price of 5.000, a very tiny one but non the less.

![bitshares-inconsistantbuyprice](https://user-images.githubusercontent.com/12114550/30922184-aa0815b2-a3a8-11e7-8172-9c2aa9b60a48.PNG)

**Comment by pmconrad** [comment] 2017-09-27 16:45
This is a known issue that happens frequently when the amounts involved. It is caused by rounding errors - BTC has 8 decimals and bitUSD has 4 - it is therefore not possible to sell .00000002 BTC for less than .0001 USD (i. e. at a price of less than $5000/BTC).

Closing as a duplicate of #342 .

**Closed by pmconrad** 2017-09-27 16:45 UTC
