### ISSUE TITLE
Memo no longer supports Chinese characters?

### ISSUE THREAD

**Issue by imYao** [bitshares/bitshares-core#283] opened 2017-05-15 14:12 UTC
![guiv chinese memo not support 20170515161635](https://cloud.githubusercontent.com/assets/5551341/26061609/fc7bd0b6-39ba-11e7-9d36-157279c18c6f.jpg)
Two Chinese characters are replaced by strange characters and numbers. Is there something wrong with text coding?

**Comment by abitmore** [comment] 2017-05-15 16:07
I think the issue is on transwiser's page. If send directly from the top menu the memo is OK. If send via transwiser's "withdraw" button/link, it's not OK.

**Comment by abitmore** [comment] 2017-05-16 06:35
Moved to https://github.com/bitshares/bitshares-ui/issues/145, closing this one.

**Closed by abitmore** 2017-05-16 06:35 UTC
