### ISSUE TITLE
Remove "no subscription warning"

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#174] opened 2017-01-18 02:40 UTC
_From @xeroc on February 16, 2016 9:0_

If you try to get an object from the witness node, it complains if you do not have subscribed to notifications.

_Copied from original issue: cryptonomex/graphene#584_

**Comment by oxarbitrage** [comment] 2017-01-30 19:17
I will like to have some more information about this issue and examples on where it is happening exactly as i can't reproduce.

First, i made a test using curl getting a witness object:

`alfredo@graphene:~/bitshares-2$ curl --data '{"jsonrpc": "2.0", "method": "get_objects", "params": [["1.6.1"]], "id": 1}' http://127.0.0.1:8090/rpc
{"id":1,"result":[{"id":"1.6.1","witness_account":"1.2.6","last_aslot":122058,"signing_key":"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","vote_id":"1:0","total_votes":0,"url":"","total_missed":0,"last_confirmed_block_num":32}]}
alfredo@graphene:~/bitshares-2$
`
No warning was shown in the output nor in the node, then i was following this:
https://github.com/bitshares/bitshares-core/wiki/Websocket-Subscriptions

The full session part, i tried without subscription, i was not able to find the warning either:

`> {"method": "call", "params": [1, "login", ["", ""]], "id": 2}
< {"id":2,"result":true}
> {"method": "call", "params": [1, "database", []], "id": 3}
< {"id":3,"result":2}
> {"method": "call", "params": [1, "history", []], "id": 4}
< {"id":4,"result":3}
> {"method": "call", "params": [2, "get_objects", [["2.1.0"]]], "id": 7}
< {"id":7,"result":[{"id":"2.1.0","head_block_number":89,"head_block_id":"00000059564ca5a279a063ba2200e15fc1010a8f","time":"2017-01-30T19:11:10","current_witness":"1.6.2","next_maintenance_time":"2017-01-31T00:00:00","last_budget_time":"2017-01-30T18:51:15","witness_budget":0,"accounts_registered_this_interval":0,"recently_missed_count":478236,"current_aslot":122215,"recent_slots_filled":"91088806220895078956728605226481804316","dynamic_flags":0,"last_irreversible_block_num":0}]}
>
`
I know the issue is old but if someone haves more information please let me know and i try to reproduce and get fixed.

**Comment by pmconrad** [comment] 2017-02-02 20:14
I see the message (in the node logs) when I connect the CLI wallet to the node and issue HTTP RPC requests against the CLI.
Like
`cli_wallet --server-rpc-endpoint=ws://127.0.0.1:9197 --rpc-http-endpoint=127.0.0.1:9097 ...`
and then in a different window
`curl --data '{"id":0,"method":"get_object","params":["1.3.104"]}' http://127.0.0.1:9097/rpc`

**Comment by oxarbitrage** [comment] 2017-02-02 22:44
hi @pmconrad thanks for responding. I followed your steps and still can't see the warning.
I made it in 3 windows, 1 running the node, 2 running the cli wallet and 3 curl to the cli wallet port. 

I can't see the warning of the subscription in the node output or either in the log files at bitshares-core/data/my-blockprod/logs/p2p/

can you send me exact message so i can search for it ? tell me also if you see it in node console output or in log files.

thanks!

**Comment by pmconrad** [comment] 2017-02-06 18:00
It seems the issue has already been fixed with this commit: https://github.com/bitshares/bitshares-core/commit/a3cfa1055edb016d8d3b80258657862668f8598f#diff-37f216b941581cfd05361cdd1e765305

I'm running an older version of the code, that's why I was able to reproduce it.

**Comment by oxarbitrage** [comment] 2017-02-06 22:36
thanks @pmconrad i am going to request to close the issue.

**Closed** 2017-02-07 12:56 UTC
