### ISSUE TITLE
Buggy feeds (may) break MPAs

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-core#1602] opened 2019-02-19 11:00 UTC
See https://open-explorer.io/#/objects/2.4.228.

It has 2 expired feeds, 1 valid one and 1 buggy one (with CER and SP as 0/0 => 1.3.0/1.3.0)

The current feed is set to the buggy one.

**Comment by clockworkgr** [comment] 2019-02-19 11:00
https://github.com/bitshares/bitshares-ui/issues/2453

**Comment by jmjatlanta** [comment] 2019-02-19 11:14
Looks as if more validation is needed in https://github.com/bitshares/bitshares-core/blob/58c0c494a61c33e5a4ec2312084322f0014b4f5b/libraries/chain/asset_evaluator.cpp#L910

rate of 0/0 is obviously invalid, and using the same asset for both base and quote is invalid as well.

**Comment by pmconrad** [comment] 2019-02-19 14:05
Probably caused by this: https://github.com/bitshares/bitshares-core/blob/test-2.0.190212/libraries/chain/db_maint.cpp#L982 from https://github.com/bitshares/bitshares-core/pull/832

IMO this is a WONTFIX because it's simply not worth it. Shouldn't happen again, can easily be fixed by either the asset owner removing the account from the feed publishers list or by having the feed publisher update their feed.

**Comment by clockworkgr** [comment] 2019-02-19 18:48
Sure, go ahead and close it.

Only reported it in case it had unexpected consequences. We'll just code around it in the UI

**Comment by pmconrad** [comment] 2019-02-19 21:13
Does the UI treat this different than MPAs that have never had a valid feed? Or does it break on those too?

**Comment by clockworkgr** [comment] 2019-02-19 23:01
> Does the UI treat this different than MPAs that have never had a valid feed? Or does it break on those too?

if their current_feed is the same then it probably breaks equally..

Its been fixed already to cover null feeds anyway

**Comment by abitmore** [comment] 2019-02-20 12:55
I think it's not due to https://github.com/bitshares/bitshares-core/blob/151e162e1af30400f9bbe12c79b28e46af1ec99e/libraries/chain/db_maint.cpp#L981-L982 but due to https://github.com/bitshares/bitshares-core/blob/151e162e1af30400f9bbe12c79b28e46af1ec99e/libraries/chain/asset_evaluator.cpp#L794-L798 since the publication time is 1970 (default/null feed). The result is expected. Similar `current_feed` can be found as well: https://open-explorer.io/#/objects/2.4.1 although `feeds` array of that asset is empty.

Also `current_feed` can be reset to default when there is no enough valid feeds:
https://github.com/bitshares/bitshares-core/blob/8c870b79db420fc90f29ce7740c0b6f1dd623c4d/libraries/chain/asset_object.cpp#L69-L77

**Comment by pmconrad** [comment] 2019-02-20 13:03
Missed the timestamp, thanks. It seems the feeds have expired anyway, so `current_feed` is supposed to be `null`.
Works as designed, closing.

**Closed by pmconrad** 2019-02-20 13:03 UTC
Labels: 3d Bug, 4a Low, won't fix
