### ISSUE TITLE
irrelevant signiture after adding new owner key

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-core#284] opened 2017-05-15 22:30 UTC
Key 1 is OWNER, ACTIVE, and MEMO
Added Key 2 as ACTIVE
Added Key 3 as OWNER

Wallet only has Key 1 and 2.  When trying to `transfer` I get the error:
```
0 exception: unspecified
3030004 tx_irrelevant_sig: irrelevant signature included
Unnecessary signature(s) detected
    {}
    th_a  transaction.cpp:296 verify_authority
```
Worked fine before adding the 2nd Owner key.

Also to note.  `get_account enki` lists only 1 owner key.  However in the webwallet and LightWallet in permissions it shows 2 keys.

**Comment by abitmore** [comment] 2017-05-16 08:43
Likely a CLI issue, so it's a duplicate of https://github.com/bitshares/bitshares-core/issues/124.

Easy to reproduce in CLI.

I thought it could be caused by an issue in `get_required_signatures` node API, but unable to reproduce from GUI, so it's likely not the case here. Although transactions can be signed with more than sufficient keys from GUI in some cases, but they will pass the verification, so at least it's consistent as [commented in the code](https://github.com/bitshares/bitshares-core/blob/2.0.160328/libraries/chain/include/graphene/chain/protocol/transaction.hpp#L135-L137).

Related discussion: https://github.com/bitshares/bitshares-core/issues/145#issuecomment-298969416.

IMHO [the code in cli wallet](https://github.com/bitshares/bitshares-core/blob/2.0.160328/libraries/wallet/wallet.cpp#L1797-L1864) is redundant and should be changed to simply call `get_potential_signatures` and `get_required_signatures` API.

**Comment by abitmore** [comment] 2017-05-16 09:05
Sample code:
```
   signed_transaction sign_transaction( signed_transaction tx, bool broadcast = false )
   {
      auto& required_keys = _remote_db->get_potential_signatures( tx, flat_set<public_key_type>() );

      //find keys from local db
      flat_set<public_key_type> available_keys;
      for( const auto& pub_key : required_keys )
      {
         auto it = _keys.find( pub_key );
         if( it != _keys.end() )
         {
            available_keys.insert( pub_key );
         }
      }
      required_keys = _remote_db->get_required_signatures( tx, available_keys );

      // sign with required_keys
      // ...
   }
```

**Comment by abitmore** [comment] 2017-05-16 09:41
In Steem this issue is addressed by [calling `minimize_required_signatures`](https://github.com/steemit/steem/blob/v0.18.4/libraries/wallet/wallet.cpp#L676-L686) although it's somehow inefficient.

By the way, in Steem there was an issue: https://github.com/steemit/steem/issues/68 which exists in BitShares as well. Above sample code will solve it. By the way again, in Steem the authority related code is being refactored: https://github.com/steemit/steem/commit/1e78f82ed11d1573adbb72beea4b3c015e8c4321
.

**Comment by oxarbitrage** [comment] 2017-08-02 21:13
relating: https://github.com/bitshares/bitshares-core/pull/321

**Comment by oxarbitrage** [comment] 2017-08-09 01:28
@Xeldal please check the comment in here: https://github.com/bitshares/bitshares-core/pull/321#issuecomment-321126129

The fix has been merged into the develop branch.

**Closed** 2017-08-10 01:33 UTC
