### ISSUE TITLE
Failed is_valid for address in get_account_history

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#159] opened 2017-01-18 00:29 UTC
_From @theoreticalbts on February 12, 2016 20:32_

A few minutes before the block time listed in #573:

```
>>> get_account_history blocktrades 100
10 assert_exception: Assert Exception
is_valid( base58str, prefix ): BTSKUBFzGx2XZyxMPVpgWeSD49dQB2Q6CqWr
    {"str":"BTSKUBFzGx2XZyxMPVpgWeSD49dQB2Q6CqWr"}
    th_a  address.cpp:37 address
```

_Copied from original issue: cryptonomex/graphene#574_

**Comment by oxarbitrage** [comment] 2017-03-06 22:16
Had been trying this as it is similar to a closed issue: https://github.com/bitshares/bitshares-core/issues/158
The reference is for transfers in Feb 12 of 2016. 

In the current bitshares versions i did:
get_account_history blocktrades 10000

And i was able to get transfers for account blocktrades starting at date 2015-12-09, so all transfers of the account from that date up to today were included in the result. 

No exception was thrown so this should be a fixed issue.

An interesting thing here related to https://github.com/bitshares/bitshares-core/issues/191 is that get_account_history returns the transfers with the newest first. 

Similar code can probably be applied to reverse the results of get_market_history. Ill post more about it on issue 191.

**Comment by kenCode-de** [comment] 2017-03-10 07:25
Closing this issue as per @oxarbitrage today

**Comment by xeroc** [comment] 2017-03-10 08:34
@kenCode-de could you please give us a little more information, please?
We do not have access to your internal communications and for future reference, it would be helpful what the solution to this problem was

**Comment by oxarbitrage** [comment] 2017-03-10 09:50
the details of the close are i nthe comment before ken:
https://github.com/bitshares/bitshares-core/issues/159#issuecomment-284551730

there is no exception thrown in the current bitshares versions, the issue is not happening anymore.

**Comment by kenCode-de** [comment] 2017-03-10 10:20
@xeroc please read the details presented. I will wait up to 24 hours before closing this issue again.

**Comment by kenCode-de** [comment] 2017-03-13 09:41
Closing this issue as per @oxarbitrage today

**Closed by kenCode-de** 2017-03-13 09:41 UTC

**Comment by xeroc** [comment] 2017-03-13 09:58
How could I miss that?! Sorry for the inconvenience
