### ISSUE TITLE
CLI wallet exceptions when decrypting memo

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#91] opened 2017-01-17 22:20 UTC
_From @theoreticalbts on September 18, 2015 20:2_

- If you can't decrypt a memo in CLI wallet, you get a backtrace.
- CLI wallet can't decrypt memos of transactions you send

_Copied from original issue: cryptonomex/graphene#325_

**Comment by vikramrajkumar** [comment] 2017-01-17 22:20
_From @bigcube on October 31, 2015 2:14_

The memo is needed for tracking and audit purposes.  It should be made available and even prioritised for a fix.

"Memos use a shared secret that can be derived from both ends knowing the pub key of the other party only .. I assume the cli-wallet tries to derive the shared secret in the wrong way such that it fails to load the other parties private key .."

**Comment by vikramrajkumar** [comment] 2017-01-17 22:20
_From @ByronAP on November 20, 2015 17:8_

This should be priority

**Comment by vikramrajkumar** [comment] 2017-01-17 22:20
_From @ByronAP on January 7, 2016 23:30_

Please fix this its killing my system with all the errors it causes.

**Comment by vikramrajkumar** [comment] 2017-01-17 22:20
_From @abitmore on January 8, 2016 6:10_

Any back trace so that we can analyse?

**Comment by vikramrajkumar** [comment] 2017-01-18 03:43
Too old

**Comment by oxarbitrage** [comment] 2018-01-30 23:27
relating https://github.com/bitshares/bitshares-core/pull/507

**Comment by oxarbitrage** [comment] 2018-01-31 15:13
i am not able to reproduce it, maybe already fixed ?

i am using different wallets in a private testnet and sending transfers from one to the other. memo is always there decrypted.

sending from wallet 1:

```
unlocked >>> transfer my-account my-account3 1 BTS "have some COREEEEE" true
...
unlocked >>> get_account_history my-account 1
get_account_history my-account 1
2018-01-31T15:11:35 Transfer 1 BTS from my-account to my-account3 -- Memo: have some COREEEEE   (Fee: 21.05468 BTS) 

unlocked >>> 
```

receiving in wallet2:

```
unlocked >>> get_account_history my-account3 1
get_account_history my-account3 1
2018-01-31T15:11:35 Transfer 1 BTS from my-account to my-account3 -- Memo: have some COREEEEE   (Fee: 21.05468 BTS) 

unlocked >>> 
```

what i am missing ?

**Comment by abitmore** [comment] 2018-01-31 22:44
The first point is easy to reproduce: connect another CLI to a node and try `get_relative_account_history blocktrades 0 1 0`.

The second point is maybe fixed.

**Comment by oxarbitrage** [comment] 2018-02-01 00:00
```
new >>> get_relative_account_history blocktrades 0 1 0
get_relative_account_history blocktrades 0 1 0
2018-01-31T23:46:12 Transfer 0.12260 BTS from blocktrades to bilthon-40   (Fee: 0.01662 BTS) 

new >>> 
```

**Comment by oxarbitrage** [comment] 2018-02-01 00:02
found it, thanks:

```
unlocked >>> get_relative_account_history blocktrades 0 4 0
get_relative_account_history blocktrades 0 4 0
100253ms th_a       wallet.cpp:2688               operator()           ] Error when decrypting memo: 10 assert_exception: Assert Exception
wallet._keys.count(op.memo->to) || wallet._keys.count(op.memo->from): Memo is encrypted to a key BTS8MmcVDiutGynSpi5vSr8tWbrTDWYWpAkTXUD24sJu45DBFLSRK or BTS62XbUwfKm5RZrqM2RGud3JaGJcoTmVHf9j1NjWwmzW5wL5kCjL not in this wallet.
    {"to":"BTS8MmcVDiutGynSpi5vSr8tWbrTDWYWpAkTXUD24sJu45DBFLSRK","from":"BTS62XbUwfKm5RZrqM2RGud3JaGJcoTmVHf9j1NjWwmzW5wL5kCjL"}
    th_a  wallet.cpp:2674 operator()
100265ms th_a       wallet.cpp:2688               operator()           ] Error when decrypting memo: 10 assert_exception: Assert Exception
wallet._keys.count(op.memo->to) || wallet._keys.count(op.memo->from): Memo is encrypted to a key BTS8MmcVDiutGynSpi5vSr8tWbrTDWYWpAkTXUD24sJu45DBFLSRK or BTS62XbUwfKm5RZrqM2RGud3JaGJcoTmVHf9j1NjWwmzW5wL5kCjL not in this wallet.
    {"to":"BTS8MmcVDiutGynSpi5vSr8tWbrTDWYWpAkTXUD24sJu45DBFLSRK","from":"BTS62XbUwfKm5RZrqM2RGud3JaGJcoTmVHf9j1NjWwmzW5wL5kCjL"}
    th_a  wallet.cpp:2674 operator()
2018-01-31T23:46:12 Transfer 0.12260 BTS from blocktrades to bilthon-40   (Fee: 0.01662 BTS) 
2018-01-31T23:46:12 Transfer 0.09056 BTS from blocktrades to bilthon-40   (Fee: 0.01662 BTS) 
2018-01-31T23:44:30 Transfer 68.05951 BTS from blocktrades to bleujay3   (Fee: 0.01662 BTS) 
2018-01-31T23:36:09 Transfer 11.38267 BTS from lovemyson20180101 to blocktrades -- could not decrypt memo   (Fee: 0.01773 BTS) 

unlocked >>> 
```

**Comment by oxarbitrage** [comment] 2018-02-01 01:26
closing by https://github.com/bitshares/bitshares-core/pull/614 for the first point and second point already fixed.

**Closed by oxarbitrage** 2018-02-01 01:26 UTC
Labels: cli

**Comment by oxarbitrage** [comment] 2018-02-01 01:31
closing by https://github.com/bitshares/bitshares-core/pull/614 for the first point and second point already fixed.
