### ISSUE TITLE
Wallet API add more features

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1537] opened 2019-01-22 21:49 UTC
**User Story**
As a `developer` and `user` of `Wallet API` I want to add more features inside `Wallet API` so that it becomes more developer friendly, more powerful and more informative.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
List of features to add:
```
        // Subscriptions
        (set_subscribe_callback)
        (set_pending_transaction_callback)
        (set_block_applied_callback)
        (cancel_all_subscriptions)

        // Blocks and transactions
        (get_block_header)
        (get_block_header_batch)
        (get_transaction)
        (get_recent_transaction_by_id)

        // Chain
        (get_chain_properties)
        (get_config)
        (get_chain_id)

        // Keys
        (get_key_references)
        (is_public_key_registered)

        // Accounts
        (get_accounts)
        (get_full_accounts)
        (get_account_by_name)
        (get_account_references)
        (lookup_account_names)
        (lookup_accounts)

        // Balances
        (get_account_balances)
        (get_balance_objects)
        (get_vested_balances)

        // Assets
        (get_assets)
        (lookup_asset_symbols)

        // Markets / feeds
        (get_margin_positions)
        (unsubscribe_from_market)
        (subscribe_to_market)
        (get_24_volume)
        (get_top_markets)
        (get_trade_history)
        (get_trade_history_by_sequence)
        (get_ticker)

        // Witnesses
        (get_witnesses)
        (get_witness_by_account)
        (lookup_witness_accounts)
        (get_witness_count)

        // Committee members
        (get_committee_members)
        (get_committee_member_by_account)
        (lookup_committee_member_accounts)
        (get_committee_count)

        // Workers
        (get_all_workers)
        (get_workers_by_account)
        (get_worker_count)

        // Votes
        (lookup_vote_ids)

        // Authority / validation
        (get_transaction_hex)
        (get_transaction_hex_without_sig)
        (get_required_signatures)
        (get_potential_signatures)
        (get_potential_address_signatures)
        (verify_authority)
        (verify_account_authority)
        (validate_transaction)
        (get_required_fees)

        // Proposed transactions
        (get_proposed_transactions)

        // Blinded balances
        (get_blinded_balances)

        // Withdrawals
        (get_withdraw_permissions_by_giver)
        (get_withdraw_permissions_by_recipient)
```
## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [x] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment] 2019-01-22 21:50
@ryanRfox assign this issue to me please.
My estimation for this huge issue is approximately around 40 hours. Thanks !

**Comment by oxarbitrage** [comment] 2019-01-22 22:05
Lot of the features to implement are already there with the same name or similar.

For example `get_account_balances` is `list_account_balances` in the wallet, `get_witnesses` is `get_witness` and so on.

Please identify the exact features you will like to add from a cli wallet user point of view, we dont want just to add more calls but valuable calls. Please note that software using the wallet api can also call the database, history, and other apis so duplicate of this calls for bots is not needed.

**Comment by cogutvalera** [comment] 2019-01-23 06:49
@oxarbitrage there in my list aren't the same features as you said, maybe similar, but not the same.
So `get_account_balances` and `list_account_balances` are different, the last one uses list of asset ids, the first one just uses all assets. So also `get_witness` and `get_witnesses` aren't the same, because `get_witness` returns just one witness by owner account name, but `get_witnesses` returns many witnesses by their ids.

So you just didn't see which parameters will be in new features. Maybe some names are similar, but their functionality is not the same. 

All features in my list are valuable ! Please describe which features in my list aren't valuable and why if you think there aren't valuable features. Thank you very much !

**Comment by oxarbitrage** [comment] 2019-01-23 12:12
If an exchange ask us to add any of those functions to the wallet we will probably do it without much questions. Making a list of all API available is too much work in my opinion. 

What about a call in the wallet to call any API , something like:

`wallet_api::call_api(api_to_call, api_function, args);`

so it can be used as:
`unlocked>> call_api "database", "get_witness", ["arg1", "arg2"]`

**Comment by cogutvalera** [comment] 2019-01-23 13:01
@oxarbitrage thanks for your idea, I thought about it too, it is nice idea, but will require more work than adding list of features as I've suggested, because different methods have different results and different arguments.

**Comment by cogutvalera** [comment] 2019-01-23 13:06
@oxarbitrage your idea is nice but won't work as standard commands work with `gethelp` method and inline documentation (I meand this Wallet API documentation https://github.com/bitshares/bitshares-core/issues/1361), so your idea is more complecated and require more work also additional work with documentation workflow for new features in Wallet API.

**Comment by oxarbitrage** [comment] 2019-01-23 13:59
I will still prefer an approach more like "as a cli wallet trader i need to have `get_ticker` because this and that", "as a witness i need `get_witness_count` to make my life easier in this situation, other witnesses will also benefit", etc.

This are sample specific requests from users that we can of course consider if they happen. Adding 50+ functions at once to the cli wallet that no user is asking for is too much to get from our resources, specially with 200+ issues open we currently have.

**Comment by cogutvalera** [comment] 2019-01-23 14:30
I prefer another approach than you @oxarbitrage , I prefer to give powerful and flexible Wallet API to developers and users so they can do more great solutions by using Wallet API and without requiring to add this kind of feature or that. More powerful and flexible Wallet API will attract more new developers and new users, do not forget about this too.
I need just do it.

**Comment by pmconrad** [comment] 2019-01-23 15:18
This proposal adds no value. All the proposed calls are available in the node API (and were probably just C&P'ed from [there](https://github.com/bitshares/bitshares-core/blob/2.0.181221/libraries/app/include/graphene/app/database_api.hpp#L744-L846) ). Any client connecting to the wallet can just as well connect a node and call them directly.
Closing.

**Comment by pmconrad** [comment] 2019-01-23 17:29
You mean your best argument is "there's already useless stuff in there so why not spend 50 hours on implementing more useless stuff"?

**Comment by cogutvalera** [comment] 2019-01-23 17:48
> You mean your best argument is "there's already useless stuff in there so why not spend 50 hours on implementing more useless stuff"?

@pmconrad NO, I just wondered why do you think it is useless stuff ? If I thought it is useless stuff I didn't create this issue.

**Comment by cogutvalera** [comment] 2019-01-23 18:14
> You mean your best argument is "there's already useless stuff in there so why not spend 50 hours on implementing more useless stuff"?

I didn't told that and I didn't mean that. My best argument I told already and why I think this stuff is valuable, but you told that it is useless, what is your best argument ? why this stuff is useless ?

**Comment by cogutvalera** [comment] 2019-01-24 05:53
@pmconrad reopen this issue please because I want to add this valuable stuff in Wallet API even without any compensation, this stuff is more important for me and for BitShares community ! Thanks !

**Comment by pmconrad** [comment] 2019-01-24 12:46
Reopening for further discussion.
My opinion remains unchanged, others may disagree.

**Comment by cogutvalera** [comment] 2019-01-24 15:21
ok thx

**Comment by cogutvalera** [comment] 2019-02-01 19:34
PR is ready here https://github.com/bitshares/bitshares-core/pull/1551

**Comment by ryanRfox** [comment] 2019-02-03 13:44
@cogutvalera I appreciate the focus of your user story in making the BitShares Project more developer friendly. However, like @pmconrad I fail to see how these changes add value to the developer experience. These API calls already exist within the `witness_node` and a developer may access them in a similar way.

The intent of the Community Claims process is for the Core Team to review submitted Issues, prioritize them, work with Community Developers to estimate effort and finally develop the solution.  I feel the Core Team are still at the review stage on this Issue and have not advanced it toward development. I intend to keep the Issue and related PR open pending further review. 

Discussion may continue herein, but further development is not advised.

**Comment by cogutvalera** [comment] 2019-02-03 19:36
ok sure let this PR be opened
Thanks !

**Comment by pmconrad** [comment] 2019-04-10 07:13
No further comments, so closing again.

**Closed by pmconrad** 2019-04-10 07:13 UTC
