### ISSUE TITLE
Transaction doesn't process after clicking confirm

### ISSUE THREAD

**Issue by compumatrix** [bitshares/bitshares-core#282] opened 2017-05-14 00:19 UTC
This issue started yesterday. Transactions does not process after being confirmed. I've tried it on both web wallet and light wallet. Already received several tickets from my team having the same problem.

Transactions involved all operations from sending funds, exchanging on the market, etc.

**Comment by oxarbitrage** [comment] 2017-05-14 11:55
pls move to https://github.com/bitshares/bitshares-ui

**Comment by abitmore** [comment] 2017-05-14 13:35
I guess it's an API server issue.

**Comment by oxarbitrage** [comment] 2017-05-14 22:09
@compumatrix can you tell us what api server are you using ? and also, can you try connecting to a different server to see if the problem is there ?

**Comment by abitmore** [comment] 2017-06-02 18:09
This is probably due to the local system clock being too slow (time in the past), especially if the transactions are signed by a cli wallet (check the system time that running the cli wallet).

**Comment by pmconrad** [comment] 2017-07-28 09:16
Most likely not a backend issue. Recommend to close unless OP comes up with more info.

**Comment by oxarbitrage** [comment] 2017-07-31 21:16
closing

**Closed by oxarbitrage** 2017-07-31 21:16 UTC
