### ISSUE TITLE
Problem with make

### ISSUE THREAD

**Issue by ying2025** [bitshares/bitshares-core#1066] opened 2018-06-17 03:06 UTC
When I make the project.The following question happen. How I solve the following problems?
/home/zhr/bitshare/bitshares-core/libraries/deterministic_openssl_rand/deterministic_openssl_rand.cpp:92:1: error: invalid conversion from ‘void ()(const void, int)’ to ‘int ()(const void, int)’ [-fpermissive]
};
^
/home/zhr/bitshare/bitshares-core/libraries/deterministic_openssl_rand/deterministic_openssl_rand.cpp:92:1: error: invalid conversion from ‘void ()(const void, int, double)’ to ‘int ()(const void, int, double)’ [-fpermissive]
libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/build.make:62: recipe for target 'libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/deterministic_openssl_rand.cpp.o' failed
make[2]: *** [libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/deterministic_openssl_rand.cpp.o] Error 1
CMakeFiles/Makefile2:790: recipe for target 'libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/all' failed
make[1]: *** [libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
zhr@ubuntu:~/bitshare/bitshares-core$ openssl version
OpenSSL 1.0.2g 1 Mar 2016

**Comment by abitmore** [comment] 2018-06-17 06:08
OS and version?
Compiler and version?

**Comment by ying2025** [comment] 2018-06-17 06:30
Unbunt18.0.4

**Comment by pmconrad** [comment] 2018-06-17 09:07
Ubuntu-18.4 is not yet supported in main branch, please check out "develop" branch and build that. Don't forget to ``git submodule update --init --recursive``.

Closing as duplicate of #835 .

**Closed by pmconrad** 2018-06-17 09:07 UTC
