### ISSUE TITLE
Build failed on develop branch commit( a52dc12617c5 "Set number of IO threads based on user parameters" )

### ISSUE THREAD

**Issue by RichardWeiYang** [bitshares/bitshares-core#1131] opened 2018-07-10 02:00 UTC
**Build Error Description**

Trying to build the develop branch while see the following error.

```
/home/unest/bitshares-core/programs/witness_node/main.cpp:241:25: error: ‘fc::asio::default_io_service_scope’ has not been declared
          if ( fc::asio::default_io_service_scope::set_default_num_threads(num_threads) != 0 )
```

I have tried several combination of core and fc. And below is a build status of these combinations

    bitshares-core             bitshares-fc          Build Status

    bf263b1                       4441e14              Success
    bf263b1                       d8437ac(master) Fail
    6549401                      4441e14              Success
    a52dc12                      4441e14               Fail

Note: a52dc12 is one commit after 6549401, which means a52dc12 introducing the failure.

Maybe this is caused by the mismatch of core and fc, while I don't see corresponding develop branch in fc. So confused about how to choose core and fc to build.

BTW, I see the build error commit is merged in to master branch, so it supposed to be build successfully on core master branch and fc master branch? While unfortunately, I seems to encounter another build error with this combination.

So generally, which branch to choose to build core and fc?

**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
 - Host OS:            Ubuntu 14.04.5 LTS 
 - Host Physical RAM   8GB
 - Source Branch/Tag:   bitshares-core develop branch commit a52dc12617c5 "Set number of IO threads based on user parameters" , bitshares-fc commit 4441e1480778 Merge pull request #32 from bitshares/abitmore-patch-1
 - OpenSSL Version:     OpenSSL 1.0.1f 6 Jan 2014
 - Boost Version:       boost_1_57_0
 - C++ Compiler:        g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4

**Steps To Reproduce**

```
cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=Debug .
make 
```

**Console Logs (optional)**

```
/home/unest/bitshares-core/programs/witness_node/main.cpp: In function ‘int main(int, char**)’:
/home/unest/bitshares-core/programs/witness_node/main.cpp:241:25: error: ‘fc::asio::default_io_service_scope’ has not been declared
          if ( fc::asio::default_io_service_scope::set_default_num_threads(num_threads) != 0 )
                         ^
```

## CORE TEAM TASK LIST
- [x] Evaluate `Build Error`
- [x] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by RichardWeiYang** [comment] 2018-07-10 09:16
Hmm...

I tried this combination, the build succeed...

bitshares-core    f503701
bitshares-fc        0a90eff

**Comment by ryanRfox** [comment] 2018-07-10 14:59
@RichardWeiYang May I request you to confirm the inclusion of this line within your build script? It should be just prior to the  `cmake` line:
```
git submodule update --init --recursive
```
Perhpas @jmjatlanta will be able to answer your question about the build matrix you provided in the description.

**Comment by jmjatlanta** [comment] 2018-07-10 20:19
I do not have an ubuntu 14 vm/box to test this on, but I suspect it is a mismatch between bitshares-core and bitshares-fc.

Yes, we do not have a develop branch of bitshares-fc.

The "normal" case is that the bitshares-core branch you checkout is tied to a specific commit of bitshares-fc. So, if you checkout a branch of bitshares-core, you should also run ``git submodule update`` to make sure that the bitshares-fc version you are compiling is one that bitshares-core expects.

It sounds as if you were able to work around the compilation problem. Please let us know here if you are still having trouble. 

Note mainly for myself: As Ubuntu 14 is not a recent release, it could also be caused by a compiler define that we don't expect (boost perhaps? I do not believe we test Ubutntu 14).

**Comment by RichardWeiYang** [comment] 2018-07-11 00:10
As mentioned in my second reply, I managed to build it with a fresh build.

```
git clone --depth=1 https://github.com/bitshares/bitshares-core.git bitshares/bitshares-core
git submodule update --init --recursive
cmake
make
```

This sounds good.

@jmjatlanta ok, so every time I update bitshares-core, I should run git submodule update. Thanks for your tips. I will keep this in mind.

**Comment by ryanRfox** [comment] 2018-07-11 02:37
@RichardWeiYang if you are comfortable with the build process now, you may close the Issue below. I'll leave it open for now in case you have related outstanding questions.

**Closed** 2018-07-11 03:01 UTC
Labels: 0 Awaiting End User Feedback, 1b User Story, 2a Discussion Needed, 3a Request, 6 Build
