### ISSUE TITLE
get_trade_history()

### ISSUE THREAD

**Issue by rmawatson** [bitshares/bitshares-core#552] opened 2017-12-28 03:46 UTC
currently this does not seem to be a problem, but with a hard limit of 100 trades being returned, when/if the volume increases to a point that more than 100 trades occur for a given time, I see no way that I would be able to make multiple requests to get > 100 trades, as the only filter available is a start and stop time which in this case would not change. I would presumably just keep getting back the first 100 trades for that timestamp.

it would almost be better if the trades were in "buckets" for a given time, where the 100 limit would refer to number of "buckets" to return rather than actual trades.

ie,

[ time1:[trade,trade,trade], time2:[trade,trade],time3:[trade,trade] ]

so a request with a limit of "3" would return the above.

this would also make it easier when making multiple requests to get a larger trade history. At the moment, I cannot be sure if the last group (by timestamp) of trades has been truncated by the limit, or if I indeed have all of the trades that happened in that time period. So the next request has to overlap.

**Comment by abitmore** [comment] 2017-12-28 16:38
Duplicate of #448.
There is a `get_trade_history_by_sequence` API got added a while back to address this issue.

**Closed by abitmore** 2017-12-28 16:38 UTC
