### ISSUE TITLE
database close unexpected exception

### ISSUE THREAD

**Issue by guanqun** [bitshares/bitshares-core#385] opened 2017-08-31 15:48 UTC
I send Ctrl+C to the witness_node, after a few minutes, it complains:

```
2655022ms th_a       db_management.cpp:170         close                ] Database close unexpected exception: {"code":3070001,"name":"pop_empty_chain","message":"there are no blocks to pop","stack":[{"context":{"level":"error","file":"db_block.cpp","line":423,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2017-08-31T15:44:15"},"format":"there are no blocks to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":431,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2017-08-31T15:44:15"},"format":"","data":{}}]}
```

Is this an expected exception?

**Comment by pmconrad** [comment] 2017-08-31 16:09
Yes, this can be ignored. Duplicate of #303 , fixed in develop branch.

**Closed by pmconrad** 2017-08-31 16:09 UTC

**Comment by guanqun** [comment] 2017-08-31 16:16
Thank you @pmconrad for the quick response.

BTW: Which branch should I follow in general? And what's the development model for bitshares? (e.g. when develop branch would be merged back into master)   I'm not sure if this is a good place to ask these questions, feel free to just ignore these...

**Comment by pmconrad** [comment] 2017-08-31 16:47
> BTW: Which branch should I follow in general?

That depends. On a production node you should generally use the latest release listed on https://github.com/bitshares/bitshares-core/releases .
If you're adventurous and/or need some of the latest API changes etc. you can use the develop branch, at your own risk of course.

The development model is not set in stone right now. We have one full-time developer (@oxarbitrage), who is managing PRs. You can always propose changes that are not related to blockchain consensus in the form of a PR, it will then be reviewed, discussed and perhaps merged into develop.
Changes that are related to consensus (i.e. require a hardfork) should first be proposed in the form of a bsip ( https://github.com/bitshares/bsips ). If they receive shareholder approval they can be implemented and submitted as a PR.

**Comment by oxarbitrage** [comment] 2017-08-31 16:58
by the way, what do you think @pmconrad on a next release by merging the develop into master ? do think it will be with the hardfork changes included or we can make a release without it ? i am thinking that we might be on time for a release with all the stuff it has been added to the develop. not sure either if this is the best channel, maybe open a new issue to discuss it, forum thread, telegram chat ? 

i am including some others that may help on deciding the next steps @abitmore , @xeroc

**Comment by pmconrad** [comment] 2017-08-31 18:49
The consensus in https://bitsharestalk.org/index.php/topic,24877.0.html seems to be that for simple bugfixes requiring a hardfork witness approval is sufficient.
I was about to suggest that we announce the plan to merge PRs #340 #348 #369 #386 in the witness telegram channel, and if nobody puts in a veto within the next 2 days or so we merge them into develop (with hardfork dates in the far future). Then I'll prepare a testnet release with a hardfork time about 1 week in the future and announce it in the witness channel. Once the testnet hardfork has passed and the witnesses are happy with their test results we can produce a master release.

**Comment by guanqun** [comment] 2017-08-31 23:51
Great info! Thank you all. 👍
