### ISSUE TITLE
Probably wrong comment

### ISSUE THREAD

**Issue by botanegg** [bitshares/bitshares-core#1301] opened 2018-09-01 14:45 UTC
Hello.
See at this line [libraries/chain/db_update.cpp#L119](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_update.cpp#L119)

Are you sure about that comment?
I think is correct multiplier is .3, because GRAPHENE_IRREVERSIBLE_THRESHOLD is 70% of GRAPHENE_100_PERCENT

**Comment by ryanRfox** [comment] 2018-09-04 19:39
Hi @botanegg and welcome. I'm the Coordinator for the Core Team. We encourage community members to assist us in identifying and resolving bugs, identifying features and enhancements, updating lacking documentation and drafting improvement proposals. Clearly, you are deep within the code, so please [learn more here](https://www.bitshares.foundation/workers/2018-03-bitshares-core) (see: Bounty Process). Also, I encourage your to review our [Project Backlog](https://github.com/bitshares/bitshares-core/projects/6) for other open Issues you may be willing to claim.

**Comment by pmconrad** [comment] 2018-09-05 15:13
The comment doesn't make much sense anyway because no two witnesses would have the same last_confirmed_block_num.

**Comment by oxarbitrage** [comment] 2018-09-28 21:00
i am not an expert in this subject but i think @botanegg is right here so i created https://github.com/bitshares/bitshares-core/pull/1349 to change the comment.

**Comment by oxarbitrage** [comment] 2018-09-28 21:01
other option can be to remove it fully but for ilustration purposes even as @pmconrad said this is not fully accurate i think we should keep.

**Comment by oxarbitrage** [comment] 2018-09-29 12:41
closed by https://github.com/bitshares/bitshares-core/pull/1349

**Closed by oxarbitrage** 2018-09-29 12:41 UTC
Labels: 1b User Story, 2c Ready for Development, 3a Request, 9a Tiny

**Comment by botanegg** [comment] 2018-10-03 07:01
LOL, nice :)
thx :+1:
