### ISSUE TITLE
Default less-than comparison of `public_key_type` is slooooowwwwww

### ISSUE THREAD

**Issue by nathanhourt** [bitshares/bitshares-core#2248] opened 2020-08-24 01:15 UTC
Updated by @abitmore: duplicate of #1371.

--- Original Message ---

Just caught this... Fwiw:

```c++
BOOST_AUTO_TEST_CASE(public_key_type_comparison) {
    flat_set<public_key_type> s1;

    for (int i = 0; i < 5; ++i)
        s1.insert(fc::ecc::private_key::generate().get_public_key());

    flat_set<public_key_type, pubkey_comparator> s2(s1.begin(), s1.end());

    const int rounds = 1'000'000;

    auto start = fc::time_point::now();
    for (int i = 0; i < rounds; ++i)
        BOOST_CHECK(s1.contains(*s1.begin()));
    auto end = fc::time_point::now();

    wlog("public_key_type default comparion: ${rounds} rounds in ${ms} ms",
         ("rounds", rounds)("ms", (end-start).count()/1000));

    start = fc::time_point::now();
    for (int i = 0; i < rounds; ++i)
        BOOST_CHECK(s2.contains(*s2.begin()));
    end = fc::time_point::now();

    wlog("public_key_type proper comparion: ${rounds} rounds in ${ms} ms",
         ("rounds", rounds)("ms", (end-start).count()/1000));
}
```

Output:
```
83440ms th_a       performance_tests.cpp:67      test_method          ] public_key_type default comparion: 1000000 rounds in 5637 ms
83772ms th_a       performance_tests.cpp:75      test_method          ] public_key_type proper comparion: 1000000 rounds in 332 ms
```

In other words, `public_key_type` has no native `operator<` defined, but `address` does and `public_key_type` converts to `address` implicitly, so `public_key_type() < public_key_type()` converts both to `address` and compares those, which means two unnecessary SHA512 calculations.

Does it matter? [See here](https://github.com/bitshares/bitshares-core/blob/349e0061300d3e65a3e3040276c321b76069e44f/libraries/protocol/transaction.cpp#L264)

**Comment by abitmore** [comment] 2020-08-24 08:34
Known issue. Unfortunately simply adding an explicit `operator<` function changes consensus. See #1151.

For use cases like `sign_state`, if it does not impact consensus, I think we can just use another comparison function to improve performance. E.G. change
```
      flat_map<public_key_type,bool>   provided_signatures;
```
to
```
      flat_map<public_key_type,bool, pubkey_comparator>   provided_signatures;
```

**Comment by abitmore** [comment] 2020-08-24 08:53
Probably a better solution is to add a faster default comparison function, and update the code that impacts consensus to use an explicit "old" comparison function.

**Comment by nathanhourt** [comment] 2020-08-24 15:57
> Known issue. Unfortunately simply adding an explicit `operator<` function changes consensus. See #1151.

I was afraid it might, which is why I didn't propose a fix. I haven't seen what consensus mechanisms are affected yet, but I haven't looked too closely yet either.

**Comment by abitmore** [comment] 2020-08-24 16:45
Actually this issue is a duplicate of https://github.com/bitshares/bitshares-core/issues/1371. We have made efforts to address it and found it was a non-issue (see #1401) so decided that we won't fix it.

Time may have changed though. If new data shows that it became an issue we may try to address it again, otherwise it's better to leave it there.

**Comment by abitmore** [comment] 2020-08-24 16:53
FWIW related issues:
* https://github.com/bitshares/bitsharesjs/issues/13
* https://github.com/bitshares/bitshares-core/issues/607
* https://github.com/cryptonomex/graphene-ui/issues/795
* https://github.com/cryptonomex/graphene/issues/630

**Comment by nathanhourt** [comment] 2020-08-24 17:28
Alright, well I'd mistakenly assumed it was new information, but since it isn't, feel free to close this issue as duplicate, or not, as you see fit. :)

**Comment by abitmore** [comment] 2020-08-25 14:39
Duplicate of #1371. Closing.

**Closed by abitmore** 2020-08-25 14:39 UTC
Labels: 0 Duplicate
