### ISSUE TITLE
Travis-CI memory reference errors in CLI Tests

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#2067] opened 2019-11-23 22:09 UTC
Travis-CI has detected some memory reference problem in the CLI wallet integration tests.  These errors cannot always be triggered.

- Some Travis results indicate that the memory reference problem is connected with the construction of the fixture.

- Other Travis results also indicate that the memory reference problem is connected with delays after app1->shutdown **in the preceding unit test**.

- The memory reference errors can be imitated outside of Travis by the inclusion of the following code (which is patently ridiculous by intentionally breaking the functionality) at the beginning of the cli_fixture constructor.

```
std::cout << "CLI_Fixture A" << std::endl;

app1->shutdown();
fc::usleep(fc::milliseconds(1000));

std::cout << "CLI_Fixture B" << std::endl;
 ```

These combined test results suggest a timing problem where the conclusion of one unit test is interfering with the startup of the next unit test as in cli_multisig_transaction-saving_keys_wallet_test, and cli_create_htlc-cli_sign_message.

**Comment by abitmore** [comment] 2019-11-24 14:26
Duplicate of https://github.com/bitshares/bitshares-core/issues/1303 ? Also see #1626.

**Comment by MichelSantos** [comment] 2019-11-25 17:20
Yes the nature of the same problem is the same as exposed by #1303 which is a problem of one instance of an object from a prior test interfering, through an as yet unconfirmed mechanism (although I have my guesses), with another instance in the subsequent test.  The fix in #1626 attempts to fix it by allowing the environment sufficient time to shut down the prior instance of the `cli_fixture` members.

However the delaying action from #1626 is absent **when the prior test** creates an `graphene::app::application` directly rather than a cli_fixture.  This causes a problem for two pairs of test sequences in the suite: cli_multisig_transaction-saving_keys_wallet_test, and cli_create_htlc-cli_sign_message.  In both cases, the prior test directly creates an instance of `graphene::app::application` and the subsequent test indirectly creates an instance of `graphene::app::application` by instantiating a `cli_fixture`.

I have no objection to leaving out this PR for now because I have high confidence at this point that the problem is in the test suite and not in the underlying objects in Core.  Please advise if you recommend to close this PR #2068 or to PR into another branch.

**Comment by abitmore** [comment] 2019-11-25 21:50
I didn't know you created another app object outside of cli_fixture. Approved #2068.

**Comment by abitmore** [comment] 2019-11-25 21:55
The underlying reason is described in OP of https://github.com/bitshares/bitshares-core/issues/1784.

**Closed** 2019-11-26 16:52 UTC
