### ISSUE TITLE
witness_node seems doesn’t work after update in test blockchain

### ISSUE THREAD

**Issue by Clementvale** [bitshares/bitshares-core#643] opened 2018-02-06 09:35 UTC
Dear BitShares developers, hope somebody can help.
We’ve just started a new forked project  https://github.com/Clementvale-LTD, it is based on previous release “BitShares Core Release 2.0.171212”
Yesterday I notice a new release “BitShares Core Release 2.0.180202” and merged changes into my fork. Seems witness_node doesn’t work anymore after update in my testsnet blockchain.
Should be next releases backward compatible with existing  databases? Or should I do some specific actions to  rebuild or upgrade database?
I have tried running witness_node with  “—replay” and  “--replay  --resync” options – nothing helps 
I'm working with my private blockchain, config.ini is very similar to that, described in article “Private Testnet Howto” http://docs.bitshares.org/testnet/private-testnet.html
Currently it is not a problem to create database from the scratch, but my task is to find a way to handle updates properly in the future, in a cases similar to this case.

Error output:
----------------------------
2014359ms th_a       witness.cpp:88                plugin_initialize    ] witness plugin:  plugin_initialize() begin
2014359ms th_a       witness.cpp:99                plugin_initialize    ] Public Key: BTS63cT48bYQSKoQmUW8bscsgoy3aSem5KggswgFbAKYUPfAef94s
2014359ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
2014359ms th_a       db_management.cpp:127         wipe                 ] Wiping database
2014359ms th_a       db_management.cpp:201         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"index.hpp","line":111,"method":"get","hostname":"","thread_name":"th_a","timestamp":"2018-02-06T09:33:34"},"format":"maybe_found != nullptr: Unable to find Object","data":{"id":"2.1.0"}}]}
2014447ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
2014484ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
2014485ms th_a       db_management.cpp:127         wipe                 ] Wiping database
2014486ms th_a       db_management.cpp:201         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"index.hpp","line":111,"method":"get","hostname":"","thread_name":"th_a","timestamp":"2018-02-06T09:33:34"},"format":"maybe_found != nullptr: Unable to find Object","data":{"id":"2.1.0"}}]}
2014556ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
2014556ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
2014556ms th_a       object_database.cpp:106       open                 ] Opening object database from /home/sm/bitshares-core/programs/witness_node/data/blockchain ...
2014557ms th_a       object_database.cpp:111       open                 ] Done opening object database.
2014557ms th_a       application.cpp:328           operator()           ] Initializing database...
2014557ms th_a       db_management.cpp:175         open                 ] 11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
2014557ms th_a       db_management.cpp:175         open                 ] data_dir: /home/sm/bitshares-core/programs/witness_node/data/blockchain 
2014557ms th_a       application.cpp:397           startup              ] Caught exception 11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
rethrow
    {"data_dir":"/home/sm/bitshares-core/programs/witness_node/data/blockchain"}
    th_a  db_management.cpp:175 open in open(), you might want to force a replay
2014558ms th_a       application.cpp:441           startup              ] 11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
rethrow
    {"data_dir":"/home/sm/bitshares-core/programs/witness_node/data/blockchain"}
    th_a  db_management.cpp:175 open
2014558ms th_a       application.cpp:1013          startup              ] 11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
rethrow
    {"data_dir":"/home/sm/bitshares-core/programs/witness_node/data/blockchain"}
    th_a  db_management.cpp:175 open
rethrow
    {}
    th_a  application.cpp:441 startup
2014558ms th_a       main.cpp:272                  main                 ] Exiting with error:
11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
rethrow
    {"data_dir":"/home/sm/bitshares-core/programs/witness_node/data/blockchain"}
    th_a  db_management.cpp:175 open
rethrow
    {}
    th_a  application.cpp:441 startup
2014558ms th_a       db_management.cpp:201         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"index.hpp","line":111,"method":"get","hostname":"","thread_name":"th_a","timestamp":"2018-02-06T09:33:34"},"format":"maybe_found != nullptr: Unable to find Object","data":{"id":"2.1.0"}}]}

**Comment by abitmore** [comment] 2018-02-06 10:40
Looks like your data dir is corrupted somehow. If you don't have a backup, perhaps the easiest way is to start from scratch again.

**Comment by Clementvale** [comment] 2018-02-06 11:17
No
Previous version works correctly with exactly the same data (I have stored data in backup). The problem is that I am not able to make updated version to run over the previously created blockchain.

**Comment by abitmore** [comment] 2018-02-06 11:57
I still think the issue is on your side.
We didn't change anything about block file parsing in this release. If the old node can replay, the new old should be able to replay as well.

**Comment by oxarbitrage** [comment] 2018-02-25 22:05
please delete data dir and start synchronizing from scratch.

**Comment by abitmore** [comment] 2018-03-25 11:46
No more info, closing so far.

**Closed by abitmore** 2018-03-25 11:46 UTC
Labels: question
