### ISSUE TITLE
[HARDFORK] changin issuer to require owner key

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#357] opened 2017-08-12 17:14 UTC
how hard would it be to modify asset_update such that changing the issuer requires the owner key?

That way a key that is used for operations (issuing etc) cannot change the issuer (ownership)

**Comment by abitmore** [comment] 2017-08-13 16:10
duplicate of #199

**Closed by abitmore** 2017-08-13 16:10 UTC
Labels: hardfork
