### ISSUE TITLE
witness_node uses two incompatible parsers for config.ini

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#149] opened 2017-01-18 00:27 UTC
_From @pmconrad on January 14, 2016 17:14_

The config.ini file used by the witness_node is parsed twice, with different parsers:
1. By bpo::parse_config_file to get the basic options
2. By boost::property_tree::ini_parser::read_ini for the logging configuration

These two parsers are not entirely compatible, which sometimes leads to the second parse failing. This results in the default logging config being used instead of that in the config file.

Specifically, the ini_parser does not support repeating options. This conflicts with the documented (in the default config file) behaviour wrt the track-account option "Account ID to track history for (may specify multiple times)".

The problem is difficult to diagnose, because the reason for the parse failure is not logged.

_Copied from original issue: cryptonomex/graphene#521_

## CORE TEAM TASK LIST
- [X] Evaluate / Prioritize Feature Request
  - [X] Assignment: @ihla 
  - [X] Effort Estimation: 4 hours
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment] 2017-10-27 10:28
@pmconrad: does https://github.com/bitshares/bitshares-core/commit/0011d5f389cda841fd3f320835fb26c43b6b44ff fixes this?

**Comment by pmconrad** [comment] 2018-02-15 13:56
Apparently steem has solved this by moving to a json format for the logging config: https://github.com/steemit/steem/releases/tag/v0.19.4rc1

**Comment by jmjatlanta** [comment] 2018-06-04 23:34
Ideas I can think of for the config.ini "repeating option" problem:
* Switch config file format (i.e. JSON)
* Change formatting for .ini entries to accept arrays of values
* Parse .ini at startup, throwing logging options into a separate file, to be read by the logging parser in a later step.
* Add an option in .ini to point to a separate file for logging settings, and have the logging parser read it.

**Comment by clockworkgr** [comment] 2018-06-04 23:36
I suggest either option 1 as a complete overhaul.

or option 4 seeing as that method is already used with api-access.json

**Comment by ihla** [comment] 2018-06-05 04:10
we have implemented the option 3, I can offer the PR if you wish

**Comment by abitmore** [comment] 2018-06-05 09:30
@ihla please do! thanks.

Before this is fixed, the workaround for node admins is to specify the required options as command line arguments instead. E.G.
> ./witness_node --witness-id="1.6.1" --witness-id="1.6.2"

**Comment by ryanRfox** [comment] 2018-06-07 18:36
I like automation, so if possible, please save my exiting config.ini file to config-<date>.ini and rewrite a new one in proper format from legacy file.

If that is too much effort, please fail on launch with exceedingly informative instr uctions to refactor the config.ini file manually.

**Comment by pmconrad** [comment] 2018-06-07 19:27
Automatic migration would be a one-time benefit for a few dozen (?) node operators. IMO not worth the effort.

IMO we can apply simple logic
* if config.ini and logging.ini both exists, use logging.ini only for logging config
* if config.ini exists but logging.ini does not, assume config.ini contains both
* if config.ini does not exist, create new config.ini (and also new logging.ini if logging.ini does not exist)

**Comment by ryanRfox** [comment] 2018-06-07 19:48
I agree with @pmconrad that the number of impacted users for this one time event does not warrent investment of time for automation. 

What is intended behavior at startup when: "config.ini exists but logging.ini does not"?
* Create default logging.ini file, parse config.ini but ignore any logging values therein, parse logging.ini, launch
* Fail to launch
  * Warn user about new ini file configuration
  * User must manually create properly configured config.ini
    * Recommend to save config.ini to config.old
    * Start/Stop node to create default config.ini and logging.ini files
    * Copy/paste relevant values into config.ini from config.old (manually)
* Other?

**Comment by pmconrad** [comment] 2018-06-07 19:57
IMO parse config ini like we do now, i. e. for both "normal" config and logging config. No need to change anything if it's working for the node operator.

**Comment by ryanRfox** [comment] 2018-06-07 20:13
That works as well. New features/parameters added into a new Release typically appear in the config.ini file. My practice has been to allow the software to create a new default config.ini file. I then copy/paste my values into the new .ini file and start it back up.

**Comment by ihla** [comment] 2018-07-24 05:07
I have some more questions regrading the implementation details: I believe the requirement is specified in this pseudo-code by @jmjatlanta 

If (config.ini does not exist)
{
    create config.ini;
    create logging.ini;
}

Parse config.ini for application configuration;

If (logging.ini exists)
{
    Parse logging.ini for logging configuration;
} 
else 
{
    Parse config.ini for logging configuration;
}

I am not sure about this: should we replace the legacy config.ini with the new config.ini + backup the legacy config.ini? I have modified the pseudo-code to provide backup and new file creation:

If (config.ini does not exist) // => fresh installation
{
    create config.ini;
    create logging.ini;
}

parse config.ini for application configuration;

If (logging.ini exists)
{
    parse logging.ini for logging configuration;
} 
else // => legacy config.ini
{
    parse config.ini for logging configuration;
    **backup legacy config.ini;
    create config.ini;
    create logging.ini;**
}

Please clarify the requirements so that I can proceed with the implementation, thx.

**Comment by jmjatlanta** [comment] 2018-07-24 13:19
My opinion was to allow the legacy config.ini to exist, and read the settings within it. Do not attempt to create the new ones. I was thinking that way so as to avoid the extra work.

It would be great to read their settings and create a new one based on their old one. If you would like to tackle that, it would be appreciated. And in that case, yes, backing up the old ones would be important. Verifying the new ones exist and are readable would also be important.

**Comment by pmconrad** [comment] 2018-07-26 13:58
See my comment above:
> Automatic migration would be a one-time benefit for a few dozen (?) node operators. IMO not worth the effort.

IOW if a config.ini exists but logging.ini does not, use only config.ini and the logging config contained therein.

**Comment by ihla** [comment] 2018-07-27 07:15
I am going to implement the option presented in the original @jmjatlanta pseudo-code according to the  @pmconrad guidance above. If I find the effort for the "automatic migration" is within my 4 hour estimate, I can offer the enhancement in other PR.

**Comment by abitmore** [comment] 2018-08-17 15:53
Now #1024 has been merged. But I'm not sure whether it completely fixed this issue. Originally,
>These two parsers are not entirely compatible, which sometimes leads to the second parse failing. This results in the default logging config being used instead of that in the config file.
>
>Specifically, the ini_parser does not support repeating options. This conflicts with the documented (in the default config file) behaviour wrt the track-account option "Account ID to track history for (may specify multiple times)".

With the patch, if I have multiple "track-account" entries in `config.ini`, what's the behavior? Still unable to parse logging config?

**Comment by pmconrad** [comment] 2018-08-18 07:32
For existing installations the behaviour will not change, i. e. if a config.ini exists and contains multiple entries with the same key, then the contained logging config will be ignored. This is deliberate, see discussion in #1024 https://github.com/bitshares/bitshares-core/pull/1024#discussion_r206579151 - node operators must manually fix such broken installations, for example by adding a logging.ini file.

New installations will have a config.ini and logging.ini generated.

**Comment by abitmore** [comment] 2018-08-23 23:01
`2.0.180823` Windows build only generates one `config.ini` file for me.

**Comment by abitmore** [comment] 2018-09-14 21:15
I think we can close this now. Related PR #1024 #1325.

**Closed by abitmore** 2018-09-14 21:15 UTC
Labels: 2b Gathering Requirements, 3d Bug, bug, logging

**Comment by bitfag** [comment] 2019-04-16 11:27
I'm running a private testnet and constantly getting logging parsing error

```
1513040ms th_a       config_util.cpp:239           load_logging_config_ ] Error parsing logging config from logging config file /var/lib/bitshares/config.ini, using default config
```

config.ini contains multiple witnesses

```
witness-id = "1.6.1"
witness-id = "1.6.2"
witness-id = "1.6.3"
witness-id = "1.6.4"
witness-id = "1.6.5"
witness-id = "1.6.6"
witness-id = "1.6.7"
witness-id = "1.6.8"
witness-id = "1.6.9"
witness-id = "1.6.10"
witness-id = "1.6.11"
```

If I'm commenting out all witnesses except the first, logging begins to work.

Bitshares version is recent, docker image 26b7a6685e66
