### ISSUE TITLE
 witness nodes network problem

### ISSUE THREAD

**Issue by xiao93** [bitshares/bitshares-core#2438] opened 2021-05-01 20:40 UTC
In some areas, running witness nodes (5.0.0, 5.1.0, 5.2.0) cannot sync blocks, and stops at Chain ID is 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8, which seems to be a network problem.

**Comment by xiao93** [comment] 2021-05-01 20:41
![image](https://user-images.githubusercontent.com/42384581/116794580-94384f00-ab00-11eb-8272-40f0523ab585.png)

**Comment by abitmore** [comment] 2021-05-01 23:50
Duplicate of #2434. Closing.

**Closed by abitmore** 2021-05-01 23:50 UTC
