### ISSUE TITLE
Bitshares-core Private Testnet: What are the requirements in order to pass a proposal?

### ISSUE THREAD

**Issue by BennyTejadaMaglaya** [bitshares/bitshares-core#1275] opened 2018-08-23 01:03 UTC
```
"required_active_approvals": [
      "1.2.0"
    ],
    "available_active_approvals": [
      "1.2.17",
      "1.2.18",
      "1.2.19",
      "1.2.20",
      "1.2.21",
      "1.2.22",
      "1.2.23",
      "1.2.24"
    ],
    "required_owner_approvals": [],
    "available_owner_approvals": [
      "1.2.17"
    ],
    "available_key_approvals": [
      "BTS64kZ3hcdJ4PNAvf5qCqrKTCoiprP5K3ULGEAfzGTC1CaD2cXEg",
      "BTS7hBPMJfULrDYwm9vhF7syEKxfdPeYMvfuqQFVUFjodoX2em3uE",
      "BTS6SHrRKdk6KvcyAeja6cL32zekUhAGErVi63xXGVKHgp9HUZKUZ",
      "BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
      "BTS7iF1rdhsgfXLbSYd6XdLb1JSSDvyj483VUETnhdDQZtCvc2URg"
    ],
    "proposer": "1.2.17"
```

****NOTE: this is taken from get_object_1.10.x

our minimum committee members is 3, they are all active witnesses.

for testing purposes, we've set the ffg:

"maintenance_interval"                        : 1440,(24mins)
"committee_proposal_review_period" : 1800secs(30mins)
"maximum_proposal_lifetime"             : 3600secs(1hour)

i would like to ask what seems to be missing in our approvals?
and what exactly is "required_owner_approvals": [ ]? since it is blank, is it the reason why our proposal does not take effect even after the proposal expired and the maintenance interval took place?****

**Comment by abitmore** [comment] 2018-08-23 01:37
Duplicate of #1274. Closing. Please don't open new issues.

**Closed by abitmore** 2018-08-23 01:37 UTC
