### ISSUE TITLE
Compilation warning in db/undo_database.hpp:69:22: throw will always call terminate()

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1237] opened 2018-08-07 10:09 UTC
**Build Error Description**
```
[ 96%] Building CXX object tests/CMakeFiles/cli_test.dir/cli/main.cpp.o
In file included from /home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/db/include/graphene/db/object_database.hpp:27:0,
                 from /home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/chain/include/graphene/chain/database.hpp:34,
                 from /home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/app/include/graphene/app/application.hpp:28,
                 from /home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/tests/cli/main.cpp:24:
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/db/include/graphene/db/undo_database.hpp: In destructor ‘graphene::db::undo_database::session::~session()’:
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/db/include/graphene/db/undo_database.hpp:69:22: warning: throw will always call terminate() [-Wterminate]
                      throw; // maybe crash..
                      ^~~~~
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/db/include/graphene/db/undo_database.hpp:69:22: note: in C++11 destructors default to noexcept
```
___________________________________________________________________________________
**Build Environment**
```
 - Host OS:             [Ubuntu 18.04 LTS]
 - Host Physical RAM    [16GB]
 - Source Branch/Tag:   [develop]
 - OpenSSL Version:     [1.1.0g 2 Nov 2017]
 - Boost Version:       [1.65.1]
 - C++ Compiler:        [gcc version (Ubuntu 7.3.0-16ubuntu3) 7.3.0]

~/Projects/Blockchain/Graphene/BitShares/bitshares-core$ ./programs/witness_node/witness_node -v
Version: 2.0.171025-minor-fix-1-1124-g0b353e0a
SHA: 0b353e0a70431f49c30bfc13469e666d0bea6da3
Timestamp: 4 days ago
SSL: OpenSSL 1.1.0g  2 Nov 2017
Boost: 1.65.1
Websocket++: 0.7.0
```
___________________________________________________________________________________
**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
```
1. Using installation guide from this https://github.com/bitshares/bitshares-core/blob/master/README.md
2. sudo apt-get update
3. sudo apt-get install autoconf cmake make automake libtool git libboost-all-dev libssl-dev g++ libcurl4-openssl-dev
4. git clone https://github.com/bitshares/bitshares-core.git
5. cd bitshares-core
6. git checkout develop
7. git submodule update --init --recursive
8. cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
9. make
```
___________________________________________________________________________________
## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`
___________________________________________________________________________________

**Comment by jmjatlanta** [comment] 2018-08-07 10:45
The portion of the log you show contains only a warning, and should not stop the compilation from completing.

Please provide the entire compilation log. As it is probably large, I recommend posting it to a site like http://pastebin.com and then posting the link to it here in this issue.

**Comment by cogutvalera** [comment] 2018-08-07 12:17
https://github.com/cogutvalera/bitshares-logs/blob/master/CMakeOutput.log

**Comment by jmjatlanta** [comment] 2018-08-07 12:27
Thank you. Can you capture all of the output of the make command? Something like:

``make > compile.log 2>&1``

and then provide a link to ``compile.log`` here?

**Comment by cogutvalera** [comment] 2018-08-07 12:42
https://github.com/cogutvalera/bitshares-logs/blob/master/compile.log

now I don't see the warning I've told about, do you know why ? or maybe should I cleanup and reset everything and after that re-compile whole project again ?

**Comment by pmconrad** [comment] 2018-08-07 13:41
The problem is that the destructor of undo_db can throw under certain circumstances. This is bad practice - destructors shouldn't ever throw. It's not really a problem for us, because undo_db has the same lifetime as the application itself.
Wouldn't mind a proper cleanup though.

**Comment by jmjatlanta** [comment] 2018-08-10 13:14
@cogutvalera were you able to find the error that prevented you from compiling? Please post it here. If you reset your project and the problem went away, please let us know and close this ticket. Thanks.

**Comment by jmjatlanta** [comment] 2018-08-13 19:09
I'm sorry. I misinterpreted the original post. I thought the compilation was failing. There is another similar (albeit harder to fix) warning in FC. I created #1246 to fix those warnings before I realized this ticket could be used.

**Comment by jmjatlanta** [comment] 2019-01-02 13:39
#1246 is somewhat a duplicate of this issue, albeit broader in scope.

**Closed by jmjatlanta** 2019-01-02 13:39 UTC
Labels: 1b User Story, 2a Discussion Needed, 3c Enhancement, 4a Low, 6 Build, code cleanup
