### ISSUE TITLE
Potential erratic order matching issue involving margin call orders

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-core#625] opened 2018-02-02 07:49 UTC
Dunno if this is discussed before but I couldn't found any old issues about this.

![snipaste_2018-02-02_16-35-42](https://user-images.githubusercontent.com/861659/35721801-240b1f06-0837-11e8-822e-cfb44b88f665.png)

If there are margin call orders waiting to be executed, the  buy order with price between call limit and margin call price will be executed on the margin call orders **at the order price**, instead of executing against lowest asks orders below the margin call order.

Possible cause: 

1. New order - 2. margin call order execution match - 3. execute. In step 1 the new order will first considered as highest bid which is even higher than lowest ask on the order book, so in step 2 the requirement of margin call order execution could be successfully met, leading to step 3.

This is completely guessed from what I could see, but I've been caught once and seems a new market bot is also being affected by placing orders on specified prices.

Ideally, the new buy orders should first match the existing orders on the order book, <s>then being considered for margin call orders.</s> then execute against the margin call order with lowest price available (margin call price in wallet UI)

**Comment by pmconrad** [comment] 2018-02-02 13:28
Possible duplicate of #338

**Comment by abitmore** [comment] 2018-02-02 13:29
I guess this ticket is either a duplicate of #338, or #343, or #583, or #606, or a combination of some or all of them. We're working on fixing them in next consensus-changing milestone. Please keep an eye. Helps are always welcome.

**Comment by abitmore** [comment] 2018-02-02 16:53
After further analysis I think this issue is related to #338, but not exactly the same. In #338 we said "matching price in favor of the taker", in this issue the favored matching prices are the limit orders but not the margin call orders.

**Comment by abitmore** [comment] 2018-04-12 22:34
Done with #829.

**Closed by abitmore** 2018-04-12 22:34 UTC
Labels: bug, hardfork
