### ISSUE TITLE
Prediction markets can suffer a black swan

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#460] opened 2017-11-04 21:46 UTC
@abitmore noticed that when a price feed for a prediction market is published, the usual black swan conditions are checked. The black swan checks disregard the is_prediction_market flag, and if the conditions are met, global settlement is triggered for the prediction market.

This behaviour does not make sense:
* PM tokens are always backed by the same number of backing tokens. A PM will be settled in the range [0,1], which means there is always sufficient collateral available.
* The actual feed price and MCR seem to be otherwise unused in a PM, so there is no reason to act upon them.

(This has happened on mainnet and testnet, which caused the recent problems.)

- [ ] http://docs.bitshares.eu/bitshares/tutorials/pm-close-manual.html should also be corrected, as right now it indicates that a price feed must be published for settling a PM.
- [ ] the pm-create-manual document needs to be revised as well

**Comment by abitmore** [comment] 2017-11-04 22:02
I thought it's a feature, so not only the issuer but also specified feed producers can global settle the PM.

**Comment by pmconrad** [comment] 2017-11-05 09:14
Hm. But the black swan settles at the ratio of the least collateralized short, which is always 1:1 in a PM. So this is a rather limited feature.

**Comment by abitmore** [comment] 2017-11-05 10:08
Agreed. Since we don't have a specification document, we can only guess. We may need to redesign this feature.

**Comment by abitmore** [comment] 2017-11-13 08:52
Need a BSIP.

**Comment by abitmore** [comment] 2017-11-21 20:23
After done more investigation, I agree this is a bug. We can fix it by disabling price feeds for prediction markets, don't need a BSIP.

The feature that global settle a prediction market via price feeds is debatable and deserves a BSIP.

By the way, need a better business model for the asset creator. Because the token can worth zero in the end, percentage market fee is not enough. This can be discussed in a BSIP as well.

**Comment by abitmore** [comment] 2018-02-09 18:29
I decided to postpone this as it's still a feature.When the outcome is 1, the 
This

**Comment by abitmore** [comment] 2018-02-09 18:41
Sorry for accidentally sent out an unfinished comment.

I decided to postpone this as it's still like a uncompleted feature.

* When the outcome of a PM is 1, the issuer can global settle with 1, or the price feed producers can feed 1 (which will trigger a black swan event then global settle at 1), the result is same.
* When the outcome of a PM is 0, the issuer can global settle with 0, but
  * the price feed producers are unable to feed 0 (which is a bit complicated to fix),
  * even if they feed a very small price e.g. 0.0001, the market won't be global settled since a small price won't trigger a black swan event.

The final fix would be:
* allow and only allow feeding 0 or 1
* when there are enough feeds, global settle at median feed price.

**Comment by abitmore** [comment] 2018-02-09 19:08
Updated the documents according to current situation, may need to update again after the issue is fixed.
* https://github.com/bitshares/docs.bitshares.org/blob/master/source/bitshares/tutorials/pm-create-manual.rst
* https://github.com/bitshares/docs.bitshares.org/blob/master/source/bitshares/tutorials/pm-close-manual.rst

**Comment by jmjatlanta** [comment] 2019-09-30 15:28
> The final fix would be:
> 
>     * allow and only allow feeding 0 or 1
> 
>     * when there are enough feeds, global settle at median feed price.

Q1: To feed 0, which you say is not easy, are you speaking of permitting 0 on one side of the equation ( removing validation in price::validate() ) and then cleaning up code to assure no divide by zero problems? Or perhaps you have in mind a way to feed 0 another way?

Q2: For your second bullet point, are you suggesting that having the required number of feeds present in a prediction market should automatically trigger global settlement?

**Comment by abitmore** [comment] 2019-09-30 19:40
@jmjatlanta I think it's better to discuss in https://github.com/bitshares/bsips/issues/42 atm.

A2Q1: IIRC, the former.
A2Q2: something like that, perhaps using a new operation is better.

**Comment by pmconrad** [comment] 2019-10-01 06:13
> The final fix would be:
> * allow and only allow feeding 0 or 1
> * when there are enough feeds, global settle at median feed price.

No. https://github.com/bitshares/bsips/issues/42 discusses a protocol change. This ticket here is about a bugfix.
The pricefeed should not load to global settlement on PMs, that's all.

**Comment by abitmore** [comment] 2019-10-11 13:42
Fixed by #2019.

**Closed by abitmore** 2019-10-11 13:42 UTC
Labels: bug, documentation, hardfork
